package metrics

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Metrics stores the Prometheus registry and handler.
type Metrics struct {
	Registry      *prometheus.Registry
	handler       http.Handler
	requests      *prometheus.CounterVec
	duration      *prometheus.HistogramVec
	inputTotal    *prometheus.CounterVec
	inputUser     *prometheus.CounterVec
	inputAccum    *prometheus.CounterVec
	inputOverhead *prometheus.CounterVec
	output        *prometheus.CounterVec
}

// New creates a metrics registry and exporter handler.
func New() *Metrics {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewGoCollector(), collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))
	requests := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_requests_total",
			Help: "Total number of OpenAI-compatible requests handled by solas.",
		},
		[]string{"model", "status"},
	)
	duration := prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "solas_request_duration_seconds",
			Help:    "Duration of OpenAI-compatible requests handled by solas.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"model"},
	)
	inputTotal := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_total_tokens_total",
			Help: "Total input tokens sent to upstream models by solas.",
		},
		[]string{"model"},
	)
	inputUser := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_user_tokens_total",
			Help: "Total input tokens estimated from the most recent user message only.",
		},
		[]string{"model"},
	)
	inputAccum := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_accumulated_tokens_total",
			Help: "Total estimated input tokens from accumulated context excluding the most recent user message.",
		},
		[]string{"model"},
	)
	inputOverhead := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_overhead_tokens_total",
			Help: "Total input overhead tokens (total input minus user input).",
		},
		[]string{"model"},
	)
	output := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_output_tokens_total",
			Help: "Total output tokens generated by solas.",
		},
		[]string{"model"},
	)
	reg.MustRegister(requests, duration, inputTotal, inputUser, inputAccum, inputOverhead, output)
	return &Metrics{
		Registry:      reg,
		handler:       promhttp.HandlerFor(reg, promhttp.HandlerOpts{}),
		requests:      requests,
		duration:      duration,
		inputTotal:    inputTotal,
		inputUser:     inputUser,
		inputAccum:    inputAccum,
		inputOverhead: inputOverhead,
		output:        output,
	}
}

// Handler returns the Prometheus scrape handler.
func (m *Metrics) Handler() http.Handler {
	return m.handler
}

// IncRequests increments request counters by model and status code.
func (m *Metrics) IncRequests(model string, status int) {
	if model == "" {
		model = "unknown"
	}
	m.requests.WithLabelValues(model, strconv.Itoa(status)).Inc()
}

// ObserveDuration records request duration by model label.
func (m *Metrics) ObserveDuration(model string, d time.Duration) {
	if model == "" {
		model = "unknown"
	}
	m.duration.WithLabelValues(model).Observe(d.Seconds())
}

// AddTokenUsage increments input and output token counters by model.
func (m *Metrics) AddTokenUsage(model string, inputTotalTokens, inputUserTokens, inputAccumulatedTokens, outputTokens int) {
	if model == "" {
		model = "unknown"
	}
	inputOverheadTokens := inputTotalTokens - (inputUserTokens + inputAccumulatedTokens)
	if inputOverheadTokens < 0 {
		inputOverheadTokens = 0
	}
	m.inputTotal.WithLabelValues(model).Add(float64(inputTotalTokens))
	m.inputUser.WithLabelValues(model).Add(float64(inputUserTokens))
	m.inputAccum.WithLabelValues(model).Add(float64(inputAccumulatedTokens))
	m.inputOverhead.WithLabelValues(model).Add(float64(inputOverheadTokens))
	m.output.WithLabelValues(model).Add(float64(outputTokens))
}
