package metrics

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Metrics stores the Prometheus registry and handler.
type Metrics struct {
	Registry      *prometheus.Registry
	handler       http.Handler
	inflightCount map[string]int64
	requests      *prometheus.CounterVec
	duration      *prometheus.HistogramVec
	inflight      *prometheus.GaugeVec
	inputTotal    *prometheus.CounterVec
	inputUser     *prometheus.CounterVec
	inputAccum    *prometheus.CounterVec
	inputOverhead *prometheus.CounterVec
	output        *prometheus.CounterVec
	powerCPU      prometheus.Gauge
	powerGPU      prometheus.Gauge
	powerTotal    prometheus.Gauge
	powerHealthy  prometheus.Gauge
	processPID    *prometheus.GaugeVec
	processCPU    *prometheus.GaugeVec
	processRSS    *prometheus.GaugeVec
}

// New creates a metrics registry and exporter handler.
func New() *Metrics {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewGoCollector(), collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))
	requests := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_requests_total",
			Help: "Total number of OpenAI-compatible requests handled by solas.",
		},
		[]string{"model", "status"},
	)
	duration := prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "solas_request_duration_seconds",
			Help:    "Duration of OpenAI-compatible requests handled by solas.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"model"},
	)
	inflight := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "solas_llm_inflight_requests",
			Help: "Current number of in-flight upstream LLM requests by llm.",
		},
		[]string{"llm"},
	)
	inputTotal := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_total_tokens_total",
			Help: "Total input tokens sent to upstream models by solas.",
		},
		[]string{"model"},
	)
	inputUser := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_user_tokens_total",
			Help: "Total input tokens estimated from the most recent user message only.",
		},
		[]string{"model"},
	)
	inputAccum := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_accumulated_tokens_total",
			Help: "Total estimated input tokens from accumulated context excluding the most recent user message.",
		},
		[]string{"model"},
	)
	inputOverhead := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_input_overhead_tokens_total",
			Help: "Total input overhead tokens (total input minus user input).",
		},
		[]string{"model"},
	)
	output := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "solas_output_tokens_total",
			Help: "Total output tokens generated by solas.",
		},
		[]string{"model"},
	)
	powerCPU := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "solas_power_cpu_watts",
		Help: "Latest device CPU power reading in watts.",
	})
	powerGPU := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "solas_power_gpu_watts",
		Help: "Latest device GPU power reading in watts.",
	})
	powerTotal := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "solas_power_total_watts",
		Help: "Latest total device power reading in watts.",
	})
	powerHealthy := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "solas_power_collector_healthy",
		Help: "Power collector health status (1 healthy, 0 unhealthy).",
	})
	processPID := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "solas_llm_process_pid",
			Help: "Resolved local process id for each configured LLM (0 if unknown).",
		},
		[]string{"llm"},
	)
	processCPU := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "solas_llm_process_cpu_percent",
			Help: "Latest sampled CPU percentage for the resolved local LLM process.",
		},
		[]string{"llm"},
	)
	processRSS := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "solas_llm_process_rss_bytes",
			Help: "Latest sampled RSS memory in bytes for the resolved local LLM process.",
		},
		[]string{"llm"},
	)
	reg.MustRegister(requests, duration, inflight, inputTotal, inputUser, inputAccum, inputOverhead, output, powerCPU, powerGPU, powerTotal, powerHealthy, processPID, processCPU, processRSS)
	return &Metrics{
		Registry:      reg,
		handler:       promhttp.HandlerFor(reg, promhttp.HandlerOpts{}),
		inflightCount: map[string]int64{},
		requests:      requests,
		duration:      duration,
		inflight:      inflight,
		inputTotal:    inputTotal,
		inputUser:     inputUser,
		inputAccum:    inputAccum,
		inputOverhead: inputOverhead,
		output:        output,
		powerCPU:      powerCPU,
		powerGPU:      powerGPU,
		powerTotal:    powerTotal,
		powerHealthy:  powerHealthy,
		processPID:    processPID,
		processCPU:    processCPU,
		processRSS:    processRSS,
	}
}

// Handler returns the Prometheus scrape handler.
func (m *Metrics) Handler() http.Handler {
	return m.handler
}

// IncRequests increments request counters by model and status code.
func (m *Metrics) IncRequests(model string, status int) {
	if model == "" {
		model = "unknown"
	}
	m.requests.WithLabelValues(model, strconv.Itoa(status)).Inc()
}

// ObserveDuration records request duration by model label.
func (m *Metrics) ObserveDuration(model string, d time.Duration) {
	if model == "" {
		model = "unknown"
	}
	m.duration.WithLabelValues(model).Observe(d.Seconds())
}

// AddTokenUsage increments input and output token counters by model.
func (m *Metrics) AddTokenUsage(model string, inputTotalTokens, inputUserTokens, inputAccumulatedTokens, outputTokens int) {
	if model == "" {
		model = "unknown"
	}
	inputOverheadTokens := inputTotalTokens - (inputUserTokens + inputAccumulatedTokens)
	if inputOverheadTokens < 0 {
		inputOverheadTokens = 0
	}
	m.inputTotal.WithLabelValues(model).Add(float64(inputTotalTokens))
	m.inputUser.WithLabelValues(model).Add(float64(inputUserTokens))
	m.inputAccum.WithLabelValues(model).Add(float64(inputAccumulatedTokens))
	m.inputOverhead.WithLabelValues(model).Add(float64(inputOverheadTokens))
	m.output.WithLabelValues(model).Add(float64(outputTokens))
}

// SetPowerSample stores the latest machine power sample gauges.
func (m *Metrics) SetPowerSample(cpuWatts, gpuWatts, totalWatts float64) {
	m.powerCPU.Set(cpuWatts)
	m.powerGPU.Set(gpuWatts)
	m.powerTotal.Set(totalWatts)
}

// SetPowerCollectorHealthy sets the collector health gauge.
func (m *Metrics) SetPowerCollectorHealthy(healthy bool) {
	if healthy {
		m.powerHealthy.Set(1)
		return
	}
	m.powerHealthy.Set(0)
}

// SetLLMProcessMetrics stores resolved local process metrics by llm.
func (m *Metrics) SetLLMProcessMetrics(llm string, pid int, cpuPercent float64, rssBytes float64) {
	if llm == "" {
		llm = "unknown"
	}
	m.processPID.WithLabelValues(llm).Set(float64(pid))
	m.processCPU.WithLabelValues(llm).Set(cpuPercent)
	m.processRSS.WithLabelValues(llm).Set(rssBytes)
}
